# Generated by Django 3.1.4 on 2020-12-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossingpathsapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floss_number', models.IntegerField()),
                ('description', models.CharField(max_length=75)),
                ('red', models.IntegerField()),
                ('blue', models.IntegerField()),
                ('green', models.IntegerField()),
                ('rgb_code', models.CharField(max_length=75)),
                ('row', models.CharField(max_length=75)),
            ],
        ),
    ]
