# Generated by Django 3.1.4 on 2020-12-17 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crossingpathsapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='follower', to='crossingpathsapi.crossinguser'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friend', to='crossingpathsapi.crossinguser'),
        ),
    ]
