# Generated by Django 3.1.4 on 2020-12-18 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossingpathsapi', '0002_floss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Floss',
            new_name='FlossColor',
        ),
    ]
