# Generated by Django 3.1.4 on 2020-12-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossingpathsapi', '0003_auto_20201218_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flosscolor',
            name='floss_number',
            field=models.CharField(max_length=75),
        ),
    ]
